name: steam_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - openjdk=11
  - conda-forge::pyspark=3.5.0
  - pymongo=4.6.1
  - numpy=1.26.2
  - matplotlib=3.8.2
  - pandas=2.1.4
  - pip:
    - findspark==2.0.1